In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
# Q1. Difference between Python List and NumPy Array

"""
A Python list can store elements of different data types.
It consumes more memory because each element is stored separately.

A NumPy array stores elements of the same data type in contiguous memory.
It is more memory efficient and much faster for numerical operations
because it uses optimized C-based implementation.
"""

import numpy as np

# Python Lists
list1 = [1, 2, 3, 4]
list2 = [5, 6, 7, 8]

list_result = [a * b for a, b in zip(list1, list2)]
print("List Multiplication:", list_result)

# NumPy Arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

array_result = arr1 * arr2
print("NumPy Array Multiplication:", array_result)

List Multiplication: [5, 12, 21, 32]
NumPy Array Multiplication: [ 5 12 21 32]


In [3]:
 #Q2. Broadcasting in NumPy

"""
Broadcasting allows NumPy to perform operations on arrays of different shapes.
NumPy automatically expands the smaller array to match the larger array.
It compares dimensions from right to left.
If dimensions are equal or one of them is 1, broadcasting works.
"""

import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

vector = np.array([10, 20, 30])

result = matrix + vector

print("Original Matrix:\n", matrix)
print("Vector:\n", vector)
print("After Broadcasting:\n", result)

Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Vector:
 [10 20 30]
After Broadcasting:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


In [4]:
# Q3. Missing Values in Pandas

"""
Missing values in Pandas represent unavailable data.
They are represented as NaN or None.

We detect missing values using isnull().
We replace missing values using fillna().
"""

import pandas as pd
import numpy as np

data = {
    "Math": [90, 85, np.nan, 70],
    "Science": [88, np.nan, 92, 75]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

print("\nMissing Values:\n", df.isnull())

df_filled = df.fillna(df.mean())
print("\nAfter Replacing Missing Values:\n", df_filled)

Original DataFrame:
    Math  Science
0  90.0     88.0
1  85.0      NaN
2   NaN     92.0
3  70.0     75.0

Missing Values:
     Math  Science
0  False    False
1  False     True
2   True    False
3  False    False

After Replacing Missing Values:
         Math  Science
0  90.000000     88.0
1  85.000000     85.0
2  81.666667     92.0
3  70.000000     75.0


In [5]:
# Q4. Boolean Indexing

"""
Boolean indexing filters rows based on conditions.
Pandas creates a Boolean mask (True/False values).
Rows with True are selected.
"""

import pandas as pd

data = {
    "Name": ["Aman", "Riya", "Raj", "Simran", "Karan"],
    "Age": [22, 25, 21, 23, 24],
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [40000, 50000, 35000, 45000, 48000],
    "Experience": [2, 4, 1, 3, 5]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

# Filter: Age > 22 AND Salary > 40000
filtered = df[(df["Age"] > 22) & (df["Salary"] > 40000)]

print("\nFiltered Data:\n", filtered)

Original DataFrame:
      Name  Age Department  Salary  Experience
0    Aman   22         IT   40000           2
1    Riya   25         HR   50000           4
2     Raj   21         IT   35000           1
3  Simran   23    Finance   45000           3
4   Karan   24         HR   48000           5

Filtered Data:
      Name  Age Department  Salary  Experience
1    Riya   25         HR   50000           4
3  Simran   23    Finance   45000           3
4   Karan   24         HR   48000           5
